/**
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class ChargeDateTimeType.
* @enum {}
* @readonly
*/
export default class ChargeDateTimeType {
    
        /**
         * value: "expiry_time"
         * @const
         */
        "expiry_time" = "expiry_time";

    
        /**
         * value: "paid_time"
         * @const
         */
        "paid_time" = "paid_time";

    
        /**
         * value: "settle_time"
         * @const
         */
        "settle_time" = "settle_time";

    
        /**
         * value: "create_time"
         * @const
         */
        "create_time" = "create_time";

    
        /**
         * value: "update_time"
         * @const
         */
        "update_time" = "update_time";

    

    /**
    * Returns a <code>ChargeDateTimeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ChargeDateTimeType} The enum <code>ChargeDateTimeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

