/**
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ElepayRestError model module.
 * @module model/ElepayRestError
 * @version 1.0
 */
class ElepayRestError {
    /**
     * Constructs a new <code>ElepayRestError</code>.
     * エラー情報
     * @alias module:model/ElepayRestError
     */
    constructor() { 
        
        ElepayRestError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ElepayRestError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ElepayRestError} obj Optional instance to populate.
     * @return {module:model/ElepayRestError} The populated <code>ElepayRestError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ElepayRestError();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * エラーコード
 * @member {String} code
 */
ElepayRestError.prototype['code'] = undefined;

/**
 * エラーメッセージ
 * @member {String} message
 */
ElepayRestError.prototype['message'] = undefined;






export default ElepayRestError;

