/**
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RefundDto from './RefundDto';

/**
 * The RefundExtDto model module.
 * @module model/RefundExtDto
 * @version 1.0
 */
class RefundExtDto {
    /**
     * Constructs a new <code>RefundExtDto</code>.
     * 返金のサマリー。複数回返金された場合、返金内容をサマリーして返します。
     * @alias module:model/RefundExtDto
     */
    constructor() { 
        
        RefundExtDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RefundExtDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RefundExtDto} obj Optional instance to populate.
     * @return {module:model/RefundExtDto} The populated <code>RefundExtDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RefundExtDto();

            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('totalCount')) {
                obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [RefundDto]);
            }
        }
        return obj;
    }


}

/**
 * 対象種類の表記
 * @member {String} object
 * @default 'refundExt'
 */
RefundExtDto.prototype['object'] = 'refundExt';

/**
 * 返金総額
 * @member {Number} amount
 */
RefundExtDto.prototype['amount'] = undefined;

/**
 * 返金回数
 * @member {Number} totalCount
 */
RefundExtDto.prototype['totalCount'] = undefined;

/**
 * 返金詳細情報
 * @member {Array.<module:model/RefundDto>} data
 */
RefundExtDto.prototype['data'] = undefined;






export default RefundExtDto;

