/**
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RefundReq model module.
 * @module model/RefundReq
 * @version 1.0
 */
class RefundReq {
    /**
     * Constructs a new <code>RefundReq</code>.
     * 返金リクエスト
     * @alias module:model/RefundReq
     */
    constructor() { 
        
        RefundReq.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RefundReq</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RefundReq} obj Optional instance to populate.
     * @return {module:model/RefundReq} The populated <code>RefundReq</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RefundReq();

            if (data.hasOwnProperty('chargeId')) {
                obj['chargeId'] = ApiClient.convertToType(data['chargeId'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Charge ID
 * @member {String} chargeId
 */
RefundReq.prototype['chargeId'] = undefined;

/**
 * 返金額。全額返金、及び amount の指定で任意の金額で返金ができます。
 * @member {Number} amount
 */
RefundReq.prototype['amount'] = undefined;

/**
 * 通貨コード (ISO_4217)
 * @member {String} currency
 */
RefundReq.prototype['currency'] = undefined;

/**
 * 返金理由
 * @member {String} reason
 */
RefundReq.prototype['reason'] = undefined;






export default RefundReq;

