/**
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ElepayRestError from './ElepayRestError';
import RefundDto from './RefundDto';

/**
 * The RefundsResponse model module.
 * @module model/RefundsResponse
 * @version 1.0
 */
class RefundsResponse {
    /**
     * Constructs a new <code>RefundsResponse</code>.
     * 返金情報リスト
     * @alias module:model/RefundsResponse
     */
    constructor() { 
        
        RefundsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RefundsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RefundsResponse} obj Optional instance to populate.
     * @return {module:model/RefundsResponse} The populated <code>RefundsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RefundsResponse();

            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('refunds')) {
                obj['refunds'] = ApiClient.convertToType(data['refunds'], [RefundDto]);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ElepayRestError.constructFromObject(data['error']);
            }
        }
        return obj;
    }


}

/**
 * 件数
 * @member {Number} total
 */
RefundsResponse.prototype['total'] = undefined;

/**
 * 返金詳細内容
 * @member {Array.<module:model/RefundDto>} refunds
 */
RefundsResponse.prototype['refunds'] = undefined;

/**
 * @member {module:model/ElepayRestError} error
 */
RefundsResponse.prototype['error'] = undefined;






export default RefundsResponse;

