/**
 * elepay API リファレンス
 * elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RefundDto model module.
 * @module model/RefundDto
 * @version 1.0
 */
class RefundDto {
    /**
     * Constructs a new <code>RefundDto</code>.
     * 返金オブジェクト
     * @alias module:model/RefundDto
     */
    constructor() { 
        
        RefundDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RefundDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RefundDto} obj Optional instance to populate.
     * @return {module:model/RefundDto} The populated <code>RefundDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RefundDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('object')) {
                obj['object'] = ApiClient.convertToType(data['object'], 'String');
            }
            if (data.hasOwnProperty('chargeId')) {
                obj['chargeId'] = ApiClient.convertToType(data['chargeId'], 'String');
            }
            if (data.hasOwnProperty('liveMode')) {
                obj['liveMode'] = ApiClient.convertToType(data['liveMode'], 'Boolean');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('refundedTime')) {
                obj['refundedTime'] = ApiClient.convertToType(data['refundedTime'], 'Number');
            }
            if (data.hasOwnProperty('createTime')) {
                obj['createTime'] = ApiClient.convertToType(data['createTime'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Refund ID
 * @member {String} id
 */
RefundDto.prototype['id'] = undefined;

/**
 * 対象種類の表記
 * @member {String} object
 * @default 'refund'
 */
RefundDto.prototype['object'] = 'refund';

/**
 * Charge ID
 * @member {String} chargeId
 */
RefundDto.prototype['chargeId'] = undefined;

/**
 * 本番モードかどうか - false テストモード - true 本番モード 
 * @member {Boolean} liveMode
 */
RefundDto.prototype['liveMode'] = undefined;

/**
 * 返金金額。全額返金、及び amount を指定することで金額の部分返金を行うことができます。
 * @member {Number} amount
 */
RefundDto.prototype['amount'] = undefined;

/**
 * 通貨コード (ISO_4217)
 * @member {String} currency
 */
RefundDto.prototype['currency'] = undefined;

/**
 * 返金理由
 * @member {String} reason
 */
RefundDto.prototype['reason'] = undefined;

/**
 * 返金状態
 * @member {String} status
 */
RefundDto.prototype['status'] = undefined;

/**
 * 返金を行う時間のUTCタイムスタンプ。
 * @member {Number} refundedTime
 */
RefundDto.prototype['refundedTime'] = undefined;

/**
 * 返金新規時間のUTCタイムスタンプ。
 * @member {Number} createTime
 */
RefundDto.prototype['createTime'] = undefined;






export default RefundDto;

